#!/bin/bash --

# enter a number larger then one and print a column
# of numbers starting from one untill that number
# is reached

LOW=3
read -p "Geef een getal groter dan $LOW in: " HIGH
while [ $LOW -ge $HIGH ]
do
    read -p "Geef een getal groter dan $LOW in: " HIGH
done

for N in $(seq $LOW $HIGH)
do
	echo $N
done
